<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~    Copyright 2014-2025 <a href="mailto:asialjim@qq.com">Asial Jim</a>
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.asialjim.microapplet</groupId>
        <artifactId>commons</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>commons-zen-dependencies</artifactId>
    <name>Commons Zen Dependencies</name>
    <packaging>pom</packaging>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-cache-redis</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-common</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-config</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-config-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-config-mybatis-flex</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-crypt</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-crypt-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-crypt-sensitive</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-mybatis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-mybatis-plus</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-mybatis-flex</artifactId>
                <version>${project.version}</version>
            </dependency>



            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-security-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-security-web</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-mvc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-tomcat</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-nacos</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-undertow</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-feign</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.asialjim.microapplet</groupId>
                <artifactId>commons-web-flux</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>